### Create product

POST http://localhost:3000/products
Content-Type: application/json

{
    "productName": "Nike Shoes",
    "productDescription": "Awesome nike running shoes",
    "price": 5000,
    "stockQuantity": 10
}

### Get few products
GET http://localhost:3000/products

### Sample HTTP call

GET http://localhost:3000