
version: '3.9'
services:
  web:

    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace:cached

    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      
    command: sleep infinity

    depends_on:
      - db

    links:
      - db:db

  db:
    image: postgres:14-alpine
    restart: unless-stopped
    ports: 
      - 5432:5432
    command: postgres -c password_encryption=md5
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-local=md5"
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: data